### ISSUE TITLE
Null pointer exception for grailsApplication while using added connections

### ISSUE THREAD

**Issue by pankaz** [grails-plugins/grails-redis#47]
Hi,

I'm using Grails 2.4.0. When I try using additional connections that are configured via the connections closures, I get a NPE at src\groovy\grails\plugin\redis\RedmineService.groovy.

I was able to fix it by using Holders.grailsApplication instead of grailsApplication. Can you kindly integrate this fix into the code base?

Thanks

**Comment by tednaleid** [comment]
released at 1.6.1.  If that doesn't fix it, please provide a test case/patch that I can use to exercise the issue.
