### ISSUE TITLE
1.6.2 regression for Grails 2.3.7

### ISSUE THREAD

**Issue by metajungle** [grails-plugins/grails-redis#49]
If I do the following:

    > mkdir ~/test
    > cd ~/test
    > grails create-app bookstore
    > cd bookstore
    > vim grails-app/conf/BuildConfig.groovy 

and then add the following:

    plugins {
        ...
        runtime ":redis:1.6.2"
    }

Then I run and get the error shown below.

If I change to: 

    plugins {
        ...
        runtime ":redis:1.6.1"
    }

**Then there are no errors.**

This is for Grails version 2.3.7 and Groovy:

    > groovy --version
    Groovy Version: 2.3.7 JVM: 1.7.0_67 Vendor: Oracle Corporation OS: Mac OS X

This is the error: 

    > grails -reloading
    grails> dev run-app
    | Running Grails application
    objc[3669]: Class JavaLaunchHelper is implemented in both     /Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/bin/java and     /Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
    | Error 2015-02-09 20:21:37,500 [localhost-startStop-1] ERROR context.GrailsContextLoader  - Error initializing the application: No signature of method: java.util.LinkedHashMap.isSet() is applicable for argument types: (java.lang.String) values: [port]
    Possible solutions: size(), size(), keySet(), keySet(), inspect(), sort()
    Message: No signature of method: java.util.LinkedHashMap.isSet() is applicable for argument types:     (java.lang.String) values: [port]
    Possible solutions: size(), size(), keySet(), keySet(), inspect(), sort()
        Line | Method
    ->>   39 | doCall                    in grails.plugin.redis.util.RedisConfigurationUtil$__clinit__closure2
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
    |     67 | doCall                    in RedisGrailsPlugin$_closure1
    |    754 | invokeBeanDefiningClosure in grails.spring.BeanBuilder
    |    584 | beans                     in     ''
    |    527 | invokeMethod . . . . . .  in     ''
    |    262 | run                       in java.util.concurrent.FutureTask
    |   1145 | runWorker . . . . . . . . in java.util.concurrent.ThreadPoolExecutor
    |    615 | run                       in java.util.concurrent.ThreadPoolExecutor$Worker
    ^    745 | run . . . . . . . . . . . in java.lang.Thread
    | Error 2015-02-09 20:21:37,663 [localhost-startStop-1] ERROR context.GrailsContextLoader  - Error initializing Grails: No signature of method: java.util.LinkedHashMap.isSet() is applicable for argument types: (java.lang.String) values: [port]
    Possible solutions: size(), size(), keySet(), keySet(), inspect(), sort()
    Message: No signature of method: java.util.LinkedHashMap.isSet() is applicable for argument types: (java.lang.String) values: [port]
    Possible solutions: size(), size(), keySet(), keySet(), inspect(), sort()
        Line | Method
    ->>   39 | doCall                    in grails.plugin.redis.util.RedisConfigurationUtil$__clinit__closure2
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
    |     67 | doCall                    in RedisGrailsPlugin$_closure1
    |    754 | invokeBeanDefiningClosure in grails.spring.BeanBuilder
    |    584 | beans                     in     ''
    |    527 | invokeMethod . . . . . .  in     ''
    |    262 | run                       in java.util.concurrent.FutureTask
    |   1145 | runWorker . . . . . . . . in java.util.concurrent.ThreadPoolExecutor
    |    615 | run                       in java.util.concurrent.ThreadPoolExecutor$

**Comment by tednaleid** [comment]
Thanks, I think this is fixed in 1.6.3 which will be released in a couple of minutes
