### ISSUE TITLE
Set connection timeout

### ISSUE THREAD

**Issue by rblazquez** [grails-plugins/grails-redis#56]
Im having problems since i have a remote instance and experiencing timeout 

redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out

In Jedis there is a way to specify a higher value using constructor:

public Jedis(final String host, final int port, final int timeout)

Can i do something similar with the plugin?

**Comment by ctoestreich** [comment]
Can you accomplish this in via the yml (grails 3) or config.groovy (grails 2)?

```
grails {
    redis {
        timeout = 10000 //default in milliseconds
        port = 6379
        host = "10.20.30.40" 
    }
}
