### ISSUE TITLE
2.0.5 not found in bintray

### ISSUE THREAD

**Issue by jack-kerouac** [grails-plugins/grails-redis#76]
The version 2.0.5 cannot be resolved. Is it correctly uploaded?

**Comment by grassjedi** [comment]
> The version 2.0.5 cannot be resolved. Is it correctly uploaded?

@jack-kerouac, this from README.md release-notes section might solve your problem:

**2.0.4 - released 02/26/2016 - Upgrading to Jedis 2.8.0 and Gson 2.6.1. Official name for package to org.grails.plugins:redis. Moved bintray location. Breaking Change**

**Comment by jack-kerouac** [comment]
Thanks for the resolution! :-) Two years after opening this issue. Will close it.
